
    import './styles.scoped.css';
    export default {
  "root": "awsui_root_1wzqe_1iw4n_141",
  "search-field": "awsui_search-field_1wzqe_1iw4n_176",
  "input-wrapper": "awsui_input-wrapper_1wzqe_1iw4n_183",
  "add-token": "awsui_add-token_1wzqe_1iw4n_190",
  "tokens": "awsui_tokens_1wzqe_1iw4n_197",
  "token-operator": "awsui_token-operator_1wzqe_1iw4n_202",
  "property-editor": "awsui_property-editor_1wzqe_1iw4n_206",
  "property-editor-header": "awsui_property-editor-header_1wzqe_1iw4n_209",
  "property-editor-header-enum": "awsui_property-editor-header-enum_1wzqe_1iw4n_222",
  "property-editor-form": "awsui_property-editor-form_1wzqe_1iw4n_237",
  "property-editor-cancel": "awsui_property-editor-cancel_1wzqe_1iw4n_242",
  "property-editor-actions": "awsui_property-editor-actions_1wzqe_1iw4n_245",
  "property-editor-enum": "awsui_property-editor-enum_1wzqe_1iw4n_253",
  "token-editor": "awsui_token-editor_1wzqe_1iw4n_258",
  "token-editor-form": "awsui_token-editor-form_1wzqe_1iw4n_265",
  "token-editor-field-property": "awsui_token-editor-field-property_1wzqe_1iw4n_268",
  "token-editor-field-operator": "awsui_token-editor-field-operator_1wzqe_1iw4n_271",
  "token-editor-field-value": "awsui_token-editor-field-value_1wzqe_1iw4n_274",
  "token-editor-multiselect-wrapper": "awsui_token-editor-multiselect-wrapper_1wzqe_1iw4n_277",
  "token-editor-multiselect-wrapper-inner": "awsui_token-editor-multiselect-wrapper-inner_1wzqe_1iw4n_282",
  "token-editor-cancel": "awsui_token-editor-cancel_1wzqe_1iw4n_286",
  "token-editor-submit": "awsui_token-editor-submit_1wzqe_1iw4n_289",
  "token-editor-actions": "awsui_token-editor-actions_1wzqe_1iw4n_292",
  "token-editor-grid": "awsui_token-editor-grid_1wzqe_1iw4n_301",
  "token-editor-grid-group": "awsui_token-editor-grid-group_1wzqe_1iw4n_338",
  "token-editor-narrow": "awsui_token-editor-narrow_1wzqe_1iw4n_341",
  "token-editor-supports-groups": "awsui_token-editor-supports-groups_1wzqe_1iw4n_350",
  "token-editor-grid-header": "awsui_token-editor-grid-header_1wzqe_1iw4n_354",
  "token-editor-grid-cell": "awsui_token-editor-grid-cell_1wzqe_1iw4n_360",
  "token-editor-add-token": "awsui_token-editor-add-token_1wzqe_1iw4n_369",
  "custom-content-wrapper": "awsui_custom-content-wrapper_1wzqe_1iw4n_373",
  "custom-control": "awsui_custom-control_1wzqe_1iw4n_377",
  "input": "awsui_input_1wzqe_1iw4n_183",
  "results": "awsui_results_1wzqe_1iw4n_385",
  "token-trigger": "awsui_token-trigger_1wzqe_1iw4n_390",
  "remove-all": "awsui_remove-all_1wzqe_1iw4n_395",
  "join-operation": "awsui_join-operation_1wzqe_1iw4n_396",
  "custom-filter-actions": "awsui_custom-filter-actions_1wzqe_1iw4n_397",
  "constraint": "awsui_constraint_1wzqe_1iw4n_401"
};
  